### ISSUE TITLE
Replace External FPS Limiter

### ISSUE THREAD

**Issue by blueminder** [blueminder/nullDCNetplayLauncher#2]
A part of what makes the nullDC netplay magic happen is by unlocking the internal frame rate limiter of the emulator, and using a third-party tool to constrict by a set fps instead of audio. This method is referred to as **Frame Over Input Delay (FOID)** by supersonicstep, according to the FGC ARCADIA NullDC Guide (accessible via the Discord).

Right now, we are using a tool called `FPS_Limiter_0.2_Remake_GUI` which was originally found on one forum or another. It works well enough, but the source isn't available for future improvement.

One potential replacement is [ThirteenAG/d3d9-wrapper](https://github.com/ThirteenAG/d3d9-wrapper), which exists in the form of a drop-in DLL. If we can turn this into a binary that can interact with observable data from nullDC through a plugin, there's a whole lot we can do to improve netplay performance ourselves.

**Comment by blueminder** [comment]
FPS Limiter replaced with D3D9 antilag DLL by [Kegetys](http://www.kegetys.net/)
Will replace with an open source one once libswirl updates on nullDc hopefully enabled savestates. Closing issue until then.

**Comment by gypherogha** [comment]
This is causing massive jumps in FPS and causing dropped inputs.
